### PR TITLE
Pax nightly fixes

### PR DESCRIPTION
**Pull request by gkroiz**
# Description

Fixing several of the pax nightly tests

# Tests
[link](http://shortn/_k3lFGZCCdK)

The screenshot above shows the three main changes to this PR.
(1), the convergence test passes with increased timeout
(2), the v5p-4 test was converted to v5p-8
(3), the v5p-16 test was converted to v5p-16
# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [X] I have performed a self-review of my code.
- [X] I have necessary comments in my code, particularly in hard-to-understand areas.
- [X] I have run one-shot tests and provided workload links above if applicable. 
- [X] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Review by RissyRan — APPROVED** [review]

**Comment by gkroiz** [comment]
@RissyRan please re-approve when you get the chance, I added appropriate testing

**Review by RissyRan — COMMENTED** [review]
Thanks Gerson! I see `c4spmd1b_pretraining` is all green. How about v5p-8 and v5p-32 tests? Can you trigger a test as well?

**Comment by gkroiz** [comment]
> Thanks Gerson! I see `c4spmd1b_pretraining` is all green. How about v5p-8 and v5p-32 tests? Can you trigger a test as well?

These are also green last time I checked, I've been switching dags due to testing multiple PRs, so their history has been removed. I can re-run

**Comment by gkroiz** [comment]
@RissyRan I updated the test link, PTAL when you get the chance

**Review by RissyRan — APPROVED** [review]
Thank you!

**Pull request merged**
