### PR TITLE
Update TPU version from String to Enum

### PR DESCRIPTION
**Pull request by RissyRan**
# Description

* Update TPU version from String to Enum 
* Other small changes: 1) remove unused import; 2) remove completed TODOs; 3) update default project name in pax to the right one.

# Tests

Please describe the tests that you ran on Cloud VM to verify changes.

**Instruction and/or command lines to reproduce your tests:** ...
Upload to Airflow and test.

**List links for your tests (use go/shortn-gen for any internal link):** ...
* TF nightly: [test](https://screenshot.googleplex.com/9DAKzSL2DijMUqa)
* Jax latest: [test](https://screenshot.googleplex.com/4JHVFsgJuejgk9o)
* TorchBench: [test](https://screenshot.googleplex.com/C7PK4uiY4FBBSmv)
* Pax: [test](https://screenshot.googleplex.com/38Q6J4HVoUU5YXf) - unfortunately, all PAX tests failed due to dependency issue

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Review by allenwang28 — COMMENTED** [review]
nit: wouldn't it be more concise if we just imported the TpuVersion enum type directly rather than having to do `vm_resource.TpuVersion` every single time?

**Comment by RissyRan** [comment]
> nit: wouldn't it be more concise if we just imported the TpuVersion enum type directly rather than having to do `vm_resource.TpuVersion` every single time?

Good question! The config file usually needs `vm_resource.TpuVersion`, `vm_resource.Zone`, `vm_resource.Project`, and `vm_resource.V5_NETWORKS` for V5s. Do you think it's better we just import vm_resource? or we import TpuVersion, Zone,  etc separately for consistency?

**Comment by allenwang28** [comment]
> > nit: wouldn't it be more concise if we just imported the TpuVersion enum type directly rather than having to do `vm_resource.TpuVersion` every single time?
> 
> Good question! The config file usually needs `vm_resource.TpuVersion`, `vm_resource.Zone`, `vm_resource.Project`, and `vm_resource.V5_NETWORKS` for V5s. Do you think it's better we just import vm_resource? or we import TpuVersion, Zone, etc separately for consistency? I will slightly prefer the former.

I feel like it would read cleaner if we can avoid having to use `vm_resource.*` constantly.

**Comment by RissyRan** [comment]
> > > nit: wouldn't it be more concise if we just imported the TpuVersion enum type directly rather than having to do `vm_resource.TpuVersion` every single time?
> > 
> > 
> > Good question! The config file usually needs `vm_resource.TpuVersion`, `vm_resource.Zone`, `vm_resource.Project`, and `vm_resource.V5_NETWORKS` for V5s. Do you think it's better we just import vm_resource? or we import TpuVersion, Zone, etc separately for consistency? I will slightly prefer the former.
> 
> I feel like it would read cleaner if we can avoid having to use `vm_resource.*` constantly.

Sure, SG. I will make the change shortly.

**Comment by RissyRan** [comment]
> > > > nit: wouldn't it be more concise if we just imported the TpuVersion enum type directly rather than having to do `vm_resource.TpuVersion` every single time?
> > > 
> > > 
> > > Good question! The config file usually needs `vm_resource.TpuVersion`, `vm_resource.Zone`, `vm_resource.Project`, and `vm_resource.V5_NETWORKS` for V5s. Do you think it's better we just import vm_resource? or we import TpuVersion, Zone, etc separately for consistency? I will slightly prefer the former.
> > 
> > 
> > I feel like it would read cleaner if we can avoid having to use `vm_resource.*` constantly.
> 
> Sure, SG. I will make the change shortly.

Done. Thanks!

**Review by allenwang28 — APPROVED** [review]

**Pull request merged**
