### PR TITLE
Change a3 cluster and its zone

### PR DESCRIPTION
**Pull request by NinaCai**
# Description

The old A3 cluster is gone, created new A3 cluster for testing. Change the name and zone of A3 cluster.

# Tests

Test on nina_dags airflow.

**Instruction and/or command lines to reproduce your tests:** 
Run dags check.

**List links for your tests (use go/shortn-gen for any internal link):** 
https://540cef12d3da42ce97b48a97401b6c83-dot-us-central1.composer.googleusercontent.com/dags/maxtext_gpu_end_to_end/grid

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Review by jonb377 — APPROVED** [review]
Thank you Nina! LGTM

**Review by will-cromar — APPROVED** [review]
Should these cluster configs live in one of the multipod-owned folders?

**Comment by NinaCai** [comment]
> Should these cluster configs live in one of the multipod-owned folders?

I am not sure about it. @jonb377 could you chime in here?

**Comment by jonb377** [comment]
It seems like multipod is the only team using xpk, the other teams are using CQR or GKE directly. The change makes sense to me, but we can take it as a follow-up.

**Pull request merged**
