### PR TITLE
Add MaxText tests for Gpt3

### PR DESCRIPTION
**Pull request by ZhiyuLi-goog**
# Description
As titled, add MaxText gpt3 test. 

# Tests

Successfully run the following e2e test in a cloud vm.
- [x] `cd maxtext; bash end_to_end/test_gpt3.sh` 

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Review by jonb377 — APPROVED** [review]
LGTM

**Comment by ZhiyuLi-goog** [comment]
@tonyjohnchen could you take a review as well. 
By the way, is there possible to see whether the new gpt3 test pass or not in airflow before merging? 
Thank you for your help!

**Comment by jonb377** [comment]
@ZhiyuLi-goog You can run the DAG in a composer env to verify if it passes. Let's sync offline.

**Review by tonyjohnchen — APPROVED** [review]
It will be nice for you to set up a local airflow env and run a quick test.

LGTM

**Comment by ZhiyuLi-goog** [comment]
Tested airflow DAGs successfully with the help from @jonb377 and @tonyjohnchen.

**Pull request merged**
