### PR TITLE
increase L4 and V100 memory

### PR DESCRIPTION
**Pull request by zpcore**
# Description

Notice L4 and V100 GKE test fail due to the memory limitation. Increase the memory.

# Tests

After the terraform apply, V100 and L4 looks good ([link](https://46c56b977f2b44158661f1ef150119c7-dot-us-central1.composer.googleusercontent.com/dags/pytorchxla-torchbench/grid?dag_run_id=scheduled__2024-06-12T11%3A00%3A00%2B00%3A00&tab=graph&task_id=torchbench-all-nvidia-l4)):
image

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Comment by zpcore** [comment]
Terraform changes have already been applied to the node pool.

**Comment by vanbasten23** [comment]
Curious what error message did you get when the memory limitation is violated?

**Review by RissyRan — APPROVED** [review]

**Comment by zpcore** [comment]
> Curious what error message did you get when the memory limitation is violated?

In the airflow UI, you can only see the docker connection got lost and never come back. However, if you check log of the node in GKE, you can see error message like `out of memory`. I don't think it is due to the GPU memory. The error message pops up while installing the models like `llama` from torchbench before testing. So I increased the CPU memory here.

**Review by will-cromar — APPROVED** [review]

**Comment by zpcore** [comment]
Terraform always complains the H100's `ephemeral_storage_local_ssd_config` as below even though we didn't modify anything:
```
  # google_container_node_pool.nvidia-h100x8 must be replaced
-/+ resource "google_container_node_pool" "nvidia-h100x8" {
      ~ id                          = "projects/cloud-ml-benchmarking/locations/us-central1/clusters/benchmarking-gpu-uc1/nodePools/nvidia-h100x8-pool" -> (known after apply)
      ~ instance_group_urls         = [
          - "https://www.googleapis.com/compute/v1/projects/cloud-ml-benchmarking/zones/us-central1-a/instanceGroupManagers/gke-benchmarking-gpu-nvidia-h100x8-po-758c310d-grp",
        ] -> (known after apply)
      ~ managed_instance_group_urls = [
          - "https://www.googleapis.com/compute/v1/projects/cloud-ml-benchmarking/zones/us-central1-a/instanceGroups/gke-benchmarking-gpu-nvidia-h100x8-po-758c310d-grp",
        ] -> (known after apply)
      + max_pods_per_node           = (known after apply)
        name                        = "nvidia-h100x8-pool"
      + name_prefix                 = (known after apply)
      ~ node_count                  = 2 -> (known after apply)
      + operation                   = (known after apply)
      ~ version                     = "1.30.0-gke.1167000" -> (known after apply)
        # (5 unchanged attributes hidden)

      ~ autoscaling {
          ~ location_policy      = "ANY" -> (known after apply)
          - total_max_node_count = 0 -> null
          - total_min_node_count = 0 -> null
            # (2 unchanged attributes hidden)
        }

      - network_config {
          - create_pod_range     = false -> null
          - enable_private_nodes = false -> null
        }

      ~ node_config {
          ~ effective_taints            = [
              - {
                  - effect = "NO_SCHEDULE"
                  - key    = "nvidia.com/gpu"
                  - value  = "present"
                },
            ] -> (known after apply)
          - enable_confidential_storage = false -> null
          ~ guest_accelerator           = [
              ~ {
                  - gpu_partition_size             = ""
                  - gpu_sharing_config             = []
                    # (3 unchanged attributes hidden)
                },
            ]
          ~ image_type                  = "COS_CONTAINERD" -> (known after apply)
          ~ labels                      = {} -> (known after apply)
          ~ local_ssd_count             = 0 -> (known after apply)
          ~ logging_variant             = "DEFAULT" -> (known after apply)
          ~ metadata                    = {
              - "disable-legacy-endpoints" = "true"
            } -> (known after apply)
          + min_cpu_platform            = (known after apply)
          - resource_labels             = {} -> null
          - resource_manager_tags       = {} -> null
          ~ service_account             = "default" -> (known after apply)
          - tags                        = [] -> null
            # (6 unchanged attributes hidden)

          - ephemeral_storage_local_ssd_config { # forces replacement
              - local_ssd_count = 16 -> null # forces replacement
            }

          - shielded_instance_config {
              - enable_integrity_monitoring = true -> null
              - enable_secure_boot          = false -> null
            }
        }

      - upgrade_settings {
          - max_surge       = 1 -> null
          - max_unavailable = 0 -> null
          - strategy        = "SURGE" -> null
        }

        # (1 unchanged block hidden)
    }
```


The issue is mentioned in https://github.com/hashicorp/terraform-provider-google/issues/17068. I will make a fix to prevent H100 get destroyed and recreate every time.

**Pull request merged**
