### PR TITLE
Restructure dags and configs by team

### PR DESCRIPTION
**Pull request by RissyRan**
# Description

As more teams onboard, restructure DAGs and configs by team to gradually weaken the concept between XLML (func, conv) tests and benchmarking tests (remove `xlml` and `benchmark` folders). 

```
|--xlml
|   |--utils
|   |   |--metric.py
|   |   |--composer.py
|   |   |--tpu.py
|   |   |--...
|   |--apis
|   |   |--gcp_config.py
|--dags
|   |--examples
|   |--pytorch_xla
|   |   |--pytorchxla_huggingface.py
|   |   |--...
|   |--solutions_team
|   |   |--flax
|   |   |   |--configs
|--deployment
|--docs
|--scripts
|--pipeline
...

```

# Tests

Please describe the tests that you ran on Cloud VM to verify changes.

**Instruction and/or command lines to reproduce your tests:** ...
Upload to Airflow and see if there is any import error

**List links for your tests (use go/shortn-gen for any internal link):** ...
Expect no errors in checks and [Airflow UI](https://screenshot.googleplex.com/6aEQJXoNtiU6fhL).

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Comment by will-cromar** [comment]
Overall this makes sense to me. One thing I'd like to clarify with this structure is which parts are a reusable library that can be used by other teams outside of this repository (`utils`), and which parts are test configurations for the teams that work out of this repository (`dags` and `configs`).

- The first should make sense if we distributed it as a package. `from utils import bigquery` is ambiguous, so we should decide on a package name that makes sense. If we want to keep the name XL ML Test for the new system, I propose `xlml` as the top level package name. (This will also make it much easier for us to build a wheel for distribution to other teams.)
- `dags` and `configs` are tightly coupled as far as I can tell. Would it make sense to move each `configs` folder under each team's subdirectory as needed? e.g. have a `pytorch_xla/configs` and a `solutions_team/jax/configs`? This will also let us make some of these config libraries' names less verbose.

My proposal would look something like this:

```
|--xlml
|   |--bigquery.py
|   |--metric.py
|   |--composer.py
|   |--tpu.py
|   |--...
|--dags
|   |--examples
|   |--pytorch_xla
|   |   |--pytorchxla_huggingface.py
|   |   |--...
|   |--solutions_team
|   |   |--flax
|   |   |   |--configs
|   |   |   |   |--supported_models.py // For a future PR: should we break up these configs by model or repository?
|   |   |   |--solutionsteam_flax_latest_supported.py
```

**Comment by RissyRan** [comment]
> |   |--solutions_team

Thanks Will! I think those make sense!

Specifically to `// For a future PR: should we break up these configs by model or repository?`

Probably repository will be a better option to next refactor. For instance, models from HF repo can leverage some common set up commands, including clone the repo, install the basic requirements, etc.

Will make the changes accordingly about: 1) change `utils` to `xlml`; 2) move `configs` under `dags`.

**Comment by RissyRan** [comment]
> Overall this makes sense to me. One thing I'd like to clarify with this structure is which parts are a reusable library that can be used by other teams outside of this repository (`utils`), and which parts are test configurations for the teams that work out of this repository (`dags` and `configs`).
> 
> * The first should make sense if we distributed it as a package. `from utils import bigquery` is ambiguous, so we should decide on a package name that makes sense. If we want to keep the name XL ML Test for the new system, I propose `xlml` as the top level package name. (This will also make it much easier for us to build a wheel for distribution to other teams.)
> * `dags` and `configs` are tightly coupled as far as I can tell. Would it make sense to move each `configs` folder under each team's subdirectory as needed? e.g. have a `pytorch_xla/configs` and a `solutions_team/jax/configs`? This will also let us make some of these config libraries' names less verbose.
> 
> My proposal would look something like this:
> 
> ```
> |--xlml
> |   |--bigquery.py
> |   |--metric.py
> |   |--composer.py
> |   |--tpu.py
> |   |--...
> |--dags
> |   |--examples
> |   |--pytorch_xla
> |   |   |--pytorchxla_huggingface.py
> |   |   |--...
> |   |--solutions_team
> |   |   |--flax
> |   |   |   |--configs
> |   |   |   |   |--supported_models.py // For a future PR: should we break up these configs by model or repository?
> |   |   |   |--solutionsteam_flax_latest_supported.py
> ```

Changes applied. Tested it on [Airflow UI](https://screenshot.googleplex.com/6aEQJXoNtiU6fhL).

```
|--xlml
|   |--utils
|   |   |--metric.py
|   |   |--composer.py
|   |   |--tpu.py
|   |   |--...
|   |--apis
|   |   |--gcp_config.py
|--dags
|   |--examples
|   |--pytorch_xla
|   |   |--pytorchxla_huggingface.py
|   |   |--...
|   |--solutions_team
|   |   |--flax
|   |   |   |--configs
|--deployment
|--docs
|--scripts
|--pipeline
...
```

**Review by will-cromar — APPROVED** [review]
Thanks!

**Pull request merged**
