### PR TITLE
Add dependencies between v5e perf tests

### PR DESCRIPTION
**Pull request by raymondzouu**
# Description

Add dependencies between v5e perf tests

# Tests
 N/A

# Checklist

Before submitting this PR, please make sure (put X in square brackets):
- [x] I have performed a self-review of my code.
- [x] I have necessary comments in my code, particularly in hard-to-understand areas.
- [x] I have run one-shot tests and provided workload links above if applicable. 
- [x] I have made or will make corresponding changes to the doc if needed.

### CODE REVIEW

**Review by jonb377 — APPROVED** [review]
LGTM, thanks for the patch Raymond!

**Comment by jonb377** [comment]
cc @RissyRan, we're hitting queueing timeouts in XPK tasks due to the volume of tests we're running.

I'm only aware of two options to address this:
1. Add dependencies between the tests, which this PR does. The downside is if one test fails/times out, downstream tests will be skipped.
2. Increase the queueing timeout. The downside here is that with a higher timeout, DAGs with multiple dependent XPK tests can take longer than 24 hours to execute.

Do you know of any other resolutions?

**Comment by RissyRan** [comment]
> * Add dependencies between the tests, which this PR does. The downside is if one test fails/times out, downstream tests will be skipped.

In the 1st approach, will the last step succeed always? i.e. post-process or clean up. If so, the next test will not be skiped.

**Comment by raymondzouu** [comment]
> > * Add dependencies between the tests, which this PR does. The downside is if one test fails/times out, downstream tests will be skipped.
> 
> In the 1st approach, will the last step succeed always? i.e. post-process or clean up. If so, the next test will not be skiped.

Oh yes the post-process should succeed regardless of model test failure, thanks!

**Pull request merged**
